language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: NVx2p/0KerdnuhDADPGJ9p1DwfUjEq8KGSooBZPU9SLEzgTMaxSfvK+LEFHwQvkwiqQfzxe2fqH7dZ9a5npvHzO+G5uXYgcudYBQIpHfNNADQguGKwKwXkaTAP9BFC9xWUCuI0bVxJIiMmf2yMg5+pQngkN9WvVyrDMdiI5FxMFoyppDRyhLOUX2UU/YqXv3zT+EB4UNg5IjaUWhsu10puwjhf8JJdNTlaXqlnofhLdfIVTcXNSv6VQcNj6ybX4CuIa9TLVP8ut2qwOvRJFh9wlqjHGtg28jSjGuifUtg6kWL8dr0RQ5IzNdUWWuNWm4ORc2vjwt7HLII7cOMnRjibVsEF5V+La47cvFXKpXTzhjmhCMioW2UZjqHWqGKVtBEwulRJFNqGxXqjR7c2P6yvzoe6WbO1o5d5O57cg3AlgvrTH9wGcY0iYZACKDJ4pi3fdku7NrrTgIh9reRwXCQBV4wTMnK0oBj72/uxx+GJhKn0iwNhmROiLUl7foYzsWkxvGOPdvL395SQfXJRU6QJocNkTpCupM41xNDzGw3dXOlkDJ8HIx24t8A6XUw9Yz//Dpzuk6iuCS2Qte5wOy/SjM5CCTPQvfYYy2eJQulptouHQi9aIMrYMPNO0WPwhlnhfraW1eB2NwzQ0Ga2zbhDh9OudgLL2iLOb81xJHhYs=
  app: exercise-gamification-a-11
  on:
    repo: uva-cs3240-s21/project-a-11
