language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: M8ph0s7O/Iujuc+6jE2EPOt2XgTzNXlfLaU3M58jvmocyNmMgOR1vO5bB2KR50I4oolFqqX1/vTdX4SgA29+GyJx1AxVXGBjTHUuNSgQg8E7afgLRB68azk7D5LB1eRAbNAwQO4C7IyOHiU01xRIkZBwkC4W6bI22UQAKw3Z6qxvm/ewIKQq/fy3w4NEu5fsOIviimU/ANy55LLlzym1Exv3XAPC4At43koHl3fJ6Fm4nCPo9etfoFF5yQhespzsyXsv2cZqsT/C6sIlKACVuHHxdFWpJZlZ3XPvDUCFzHIFf73mBr4LAu2viSz3pkbyMvmEP3E6ceRAF6qcZ24ya6zvj9SD4ivemyFd3yG5nKFtBV8iF66HiKyGGVd6Ylnr2uIP0OeH2MEbAj4cTq3vgwiGs18QYAvRNJWBse+jpo1yTzONCzY4siNg2d6A1azkxhCir7cnDvPU16V6Uz3TZYAJo/KGd/awOKwN5s8lRWyNhIt6gIjuhBpwwoSUDtCIk/cKWbjRwLXtKCNvBm3k/mrM0Sm0ke9LT8k1agr5WqEwZNKyD6HaIdkQRilN9w5+JeHUY58wFE83BCgnp6clnoZIM9iJBDeCNykPI80Meom6H/5HvQwFNFTuRUO3uOKqA/9EKB1x8o9+DzJOoyZwn/abtIJPWo4sRrCAyVT5dnM=
  app: exercise-gamification-a-11
  on:
    all_branches: true
    repo: uva-cs3240-s21/project-a-11
