# Generated by Django 3.1.6 on 2021-03-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_date',
            field=models.DateField(null=True, verbose_name='date completed'),
        ),
    ]
