# Generated by Django 3.1.5 on 2021-03-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
