# Generated by Django 3.1.5 on 2021-03-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wk_points',
            field=models.IntegerField(default=0),
        ),
    ]
