# Generated by Django 3.1.5 on 2021-03-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_profile_wk_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wk_points',
            new_name='workout_points',
        ),
    ]
