# Generated by Django 3.1.6 on 2021-03-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20210315_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(default='daily workout', max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('CAR', 'cardio'), ('STR', 'strength'), ('SPT', 'sports'), ('FLX', 'yoga/flexibility')], default='CAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
