# Generated by Django 3.1.5 on 2021-03-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20210323_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
