# Generated by Django 3.1.5 on 2021-03-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20210323_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.profile'),
        ),
    ]
