# Generated by Django 3.1.5 on 2021-03-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
