# Generated by Django 3.1.5 on 2021-03-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_exercise_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='profile',
        ),
    ]
