# Generated by Django 3.1.5 on 2021-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20210321_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
