# Generated by Django 3.1.5 on 2021-03-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_exercise_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
