# Generated by Django 3.1.5 on 2021-03-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_auto_20210321_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='total_time',
        ),
    ]
