# Generated by Django 3.1.5 on 2021-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
