# Generated by Django 3.1.5 on 2021-03-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_exercise_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='total_points',
        ),
    ]
