# Generated by Django 3.1.5 on 2021-03-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_auto_20210321_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
