# Generated by Django 3.1.5 on 2021-03-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_exercise_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='total_time',
        ),
    ]
