# Generated by Django 3.1.5 on 2021-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0018_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='location',
            field=models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside')], default='INSIDE', max_length=7),
        ),
    ]
