# Generated by Django 3.1.5 on 2021-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0020_auto_20210329_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('CAR', 'Cardio'), ('STR', 'Strength'), ('SPT', 'Sports'), ('FLX', 'Yoga/Flexibility')], default='CAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_taken',
            field=models.CharField(choices=[('LESS_THAN_30', 'Quick Workout (Between 1-29 min)'), ('LESS_THAN_1_HR', 'Longer Workout (Between 30-59 min)'), ('BETWEEN_1_AND_2_HRS', 'Long Workout (Between 60 and 119 min)'), ('MORE_THAN_2_HRS', 'Very Long Workout (120 min or greater)')], default='LESS_THAN_30', max_length=20),
        ),
    ]
