# Generated by Django 3.1.5 on 2021-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0021_auto_20210329_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Sports', 'Sports'), ('Yoga/Flexibility', 'Yoga/Flexibility')], default='Cardio', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='location',
            field=models.CharField(choices=[('Indoors', 'Indoors'), ('Outdoors', 'Outdoors')], default='Indoors', max_length=8),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_taken',
            field=models.CharField(choices=[('Quick Workout (Between 1-29 min)', 'Quick Workout (Between 1-29 min)'), ('Longer Workout (Between 30-59 min)', 'Longer Workout (Between 30-59 min)'), ('Long Workout (Between 60 and 119 min)', 'Long Workout (Between 60 and 119 min)'), ('Very Long Workout (120 min or greater)', 'Very Long Workout (120 min or greater)')], default='Quick Workout (Between 1-29 min)', max_length=100),
        ),
    ]
