# Generated by Django 3.1.5 on 2021-04-08 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0023_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
