# Generated by Django 3.1.5 on 2021-04-08 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0024_exercise_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
