# Generated by Django 3.1.5 on 2021-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0025_auto_20210407_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_workouts',
            field=models.IntegerField(default=0),
        ),
    ]
