# Generated by Django 3.1.5 on 2021-04-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0026_profile_num_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_points',
            field=models.IntegerField(default=0),
        ),
    ]
