# Generated by Django 3.1.5 on 2021-04-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0027_profile_avg_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(max_length=1000),
        ),
    ]
