# Generated by Django 3.1.5 on 2021-04-19 13:12

from django.db import migrations, models
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0029_profile_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, validators=[exercise.models.validate_hash]),
        ),
    ]
