# Generated by Django 3.1.5 on 2021-04-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0030_auto_20210419_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='access_level',
        ),
    ]
