# Generated by Django 3.1.5 on 2021-04-22 23:02

from django.db import migrations, models
import django.db.models.deletion
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0031_remove_post_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.profile'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_date',
            field=models.DateTimeField(null=True, validators=[exercise.models.Exercise.exclude_future_date], verbose_name='date completed'),
        ),
    ]
